name: Build
on:
  push:
    paths-ignore:
      - README.md

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: zulu
          java-version: 11
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
